name: Build JBFramelabs APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get project
        uses: actions/checkout@v4

      - name: Extract Android project
        run: |
          unzip -q JBFramelabs_Android_Source.zip
          cd cd JBFramelabs_Android_Source
          echo "PROJECT_DIR=$PWD" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          gradle --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JBFramelabs-Magnet-Maker-APK
          path: path: JBFramelabs_Android_Source/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
